[package]
name = "app"
version = "0.1.0"
authors = ["Boris Serebrov <serebrov@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.8"
scraper = "0.9.0"
select = "0.4.2"
actix-web = { version = "0.7", features = ["alpn", "tls"] }
futures = "0.1.25"
