[package]
name = "app"
version = "0.1.0"
authors = ["Boris Serebrov <serebrov@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.1.25"
scraper = "0.9.0"
actix-web = { version = "0.7", features = ["alpn", "tls"] }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
reqwest = "0.9.8"
